記事一覧を作成しました
shinonome-inc/mobile_Mio_azuma_basic_flutter pull request #2
Opened 2024-02-10 06:50 UTC by azuma502

## 概要：記事一覧を作成しました

## CLIENT_IDとCLIENT_SECRET

## 実装した内容：記事一覧を作成しました

## UI
![Screenshot_1707531107](https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/assets/114731756/395d1d97-9e5f-477e-a4d9-97835936a117)

## 動作確認

## 参考

## その他

2024-02-10 10:22 UTC, KobayashiYoh reviewed
コメントしました

2024-02-10 10:22 UTC, KobayashiYoh commented on qiita_app/lib/repository/qiita_repository.dart
> +      // debugPrint('Response body: ${response.body}');
不要なコードはコメントアウトではなく削除しておきましょう

2024-02-10 10:24 UTC, IwaseMio reviewed
コメントしました！

2024-02-10 10:24 UTC, IwaseMio commented on qiita_app/lib/widgets/article_container.dart
> +                          ),
textのスタイルを再利用して短くするといいんじゃないかなと思いまいた！

```suggestion
                      final TextStyle commonTextStyle = TextStyle(
  fontSize: 12,
  color: AppColors.secondary,
);

Text(
  '＠${article.userName}',
  style: commonTextStyle,
),
Text(
  '投稿日:${article.postedDate}',
  style: commonTextStyle,
),
Text(
  'いいね：${article.likesCount}',
  style: commonTextStyle,
),
```

2024-02-10 15:42 UTC, KobayashiYoh commented on qiita_app/lib/repository/qiita_repository.dart
> +      // debugPrint('Response body: ${response.body}');
↑これレビューじゃなくてテスト投稿です

2024-02-14 22:05 UTC, iu-yusei commented on qiita_app/lib/repository/qiita_repository.dart
>      if (response.statusCode == 200) {
[IMO] 現時点では、開発者がデバッグできれば良いので、細かいエラーハンドリングは必要ないですが、、、
ステータスコードごとに、適切なメッセージを返す処理を実装しておくと、後の工数削減に繋がります🧑‍💻

あくまで一例ですが、こんなイメージです。

```dart
 try {
      final response = await http.get(url);

      if (response.statusCode == 200) {
        final List<dynamic> jsonResponse = jsonDecode(response.body);
        return jsonResponse.map((data) => Article.fromJson(data)).toList();
      } else {
        // ステータスコードに応じたエラーメッセージを設定
        switch (response.statusCode) {
          case 400:
            throw Exception('Bad request. Please check the request format and try again.');
          case 401:
            throw Exception('Unauthorized. You might not have permission to access the data.');
          case 403:
            throw Exception('Forbidden. Access to the requested resource is denied.');
          case 404:
            throw Exception('Not found. The requested resource could not be found.');
          case 500:
            throw Exception('Internal Server Error. Please try again later.');
          default:
            throw Exception('Failed to fetch Qiita items. Status code: ${response.statusCode}');
        }
      }
    } catch (e) {
      // 例外が発生した場合のエラーハンドリング
      debugPrint('Exception caught: $e');
      throw Exception('Failed to load Qiita items: $e');
    }

```

このようにエラーハンドリングを実装しておくと、原因特定が速くなるので、デバッグのスピードが向上します！

また、UXの観点でもメリットがあります！

**「何をすべきか、何が原因で意図した操作を完了できなかったのか」を明確に示してくれるアプリ**の方が、
ユーザーにとって優しいアプリになるので、[**モーダル上で加工済みのエラーメッセージを表示し、ユーザーにネクストアクションを促す手法**](https://bibinbaleo.hatenablog.com/entry/2021/04/05/214846) はよく使われています。

この前段階として、[ステータスコードを起点にしたエラーハンドリング](https://zenn.dev/ryamakuchi/articles/111aa3f125e507#%E3%82%AF%E3%83%A9%E3%82%A4%E3%82%A2%E3%83%B3%E3%83%88%E3%82%A8%E3%83%A9%E3%83%BC%E3%83%AC%E3%82%B9%E3%83%9D%E3%83%B3%E3%82%B9%EF%BC%88400%E7%B3%BB%EF%BC%89)を実装しておきます！

現段階で、要件以上のことを実装する必要はありませんが、この辺りを意識しながら課題に取り組んでみると、東さんのコードにさらに磨きがかかると思います✨

ご参考までに、、、

2024-02-14 22:13 UTC, iu-yusei commented on qiita_app/lib/widgets/text_bold_size_m.dart
> +  const TextBoldSizeM({
【NITS】すごく細かい話なので、修正は任意ですが、
Figmaでは下記のようにフォントが設定されているので、fontWeightは500で指定できると良いと思います！

※FontWeight.boldの値は weight 700で設定されています。
```dart
 /// A commonly used font weight that is heavier than normal.
  static const FontWeight bold = w700;
```


```css
font-family: Noto Sans JP;
font-size: 14px;
font-weight: 500;
line-height: 20px;
letter-spacing: 0.25px;
text-align: left;
```

TextBoldSizeSも同様です！
```css
font-family: Noto Sans JP;
font-size: 12px;
font-weight: 500;
line-height: 24px;
letter-spacing: 0px;
text-align: justified;

```

ref. https://www.figma.com/file/r22atGeJ5LpGwOUbYXXOPw/Mobile-Qiita-App?type=design&node-id=9362-26033&mode=design&t=Dn6dhtnhimZgZNXv-0

2024-02-14 22:14 UTC, iu-yusei commented on qiita_app/lib/widgets/text_regular_size_s.dart
> +  const TextRegularSizeS({
こちらも同様にweight 500にできると良いと思います！
```css
font-family: Noto Sans JP;
font-size: 12px;
font-weight: 500;
line-height: 24px;
letter-spacing: 0px;
text-align: justified;

```

ref. https://www.figma.com/file/r22atGeJ5LpGwOUbYXXOPw/Mobile-Qiita-App?type=design&node-id=9362-26033&mode=design&t=Dn6dhtnhimZgZNXv-0

2024-02-14 22:16 UTC, iu-yusei commented
全体的に読みやすく、変更に強いコードになっていて、とても素晴らしいです！
LGTMです🎉

いくつかコメントしたので確認お願いします！
修正は任意です！

## エラーハンドリングについて

- https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/pull/2#discussion_r1490122458


## フォントスタイルについて

- https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/pull/2#discussion_r1490130210

- https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/pull/2#discussion_r1490131110

2024-02-15 14:47 UTC, azuma502 commented on qiita_app/lib/repository/qiita_repository.dart
>      if (response.statusCode == 200) {
なるほど！！
詳しくありがとうございます！！

2024-02-15 14:54 UTC, azuma502 commented on qiita_app/lib/widgets/text_bold_size_m.dart
> +  const TextBoldSizeM({
デフォルトですでに設定されているの気がつかなかったです、、
ありがとうございます！！

2024-02-15 15:06 UTC, azuma502 commented on qiita_app/lib/widgets/text_regular_size_s.dart
> +  const TextRegularSizeS({
設定しました！

2024-02-15 15:15 UTC, azuma502 commented
レビューを踏まえて、修正しました！

2024-02-15 16:10 UTC, KobayashiYoh requested changes
コメントしました

2024-02-15 16:10 UTC, KobayashiYoh commented on qiita_app/lib/constants/app_colors.dart
> +  static const divider = Color(0xFFE0E0E0);
`main.dart`のthemeを上手く使うとWidgetのデフォルトのテーマを変更することができます
例えば、themeを以下のようにしておくと、アプリ内の全Dividerのデフォルトの色が変更されるため、おススメです！
修正は任意です
```dart
dividerColor: AppColors.divider,
```
https://github.com/KobayashiYoh/document_manager/blob/develop/lib/main.dart#L37

2024-02-15 16:10 UTC, KobayashiYoh commented on qiita_app/lib/pages/feed_page.dart
> +  }
苦戦する方が多い箇所ですが、上手く綺麗に状態管理とAPI通信が実装できています👍

2024-02-15 16:10 UTC, KobayashiYoh commented on qiita_app/lib/repository/qiita_repository.dart
> +                'Failed to fetch Qiita items. Status code: ${response.statusCode}');
今後、FeedPage以外のエンドポイント（タグやマイページ等）を利用することを考えると、メッセージ部分を関数として共通化しておくなどして汎用性を高めておくと後でラクできますよ
修正は任意です
```dart
class QiitaRepository {
  static String _exceptionMessage(int statusCode) {
    debugPrint('Status code: $statusCode');
    switch (statusCode) {
      case 400:
        return 'Bad request. Please check the request format and try again.';
      case 401:
        return 'Unauthorized. You might not have permission to access the data.';
      case 403:
        return 'Forbidden. Access to the requested resource is denied.';
      case 404:
        return 'Not found. The requested resource could not be found.';
      case 500:
        return 'Internal Server Error. Please try again later.';
      default:
        return 'Failed to make request.';
    }
  }

  static Future<List<Article>> fetchQiitaItems() async {
    final url = Uri.parse('${Urls.qiitaBaseUrl}/items');
    try {
      final response = await http.get(url);

      if (response.statusCode == 200) {
        final List<dynamic> jsonResponse = jsonDecode(response.body);
        return jsonResponse.map((data) => Article.fromJson(data)).toList();
      } else {
        // ステータスコードに応じたエラーメッセージを設定
        throw Exception(_exceptionMessage(response.statusCode));
      }
    } catch (e) {
      // 例外が発生した場合のエラーハンドリング
      throw Exception('Failed to load Qiita items: $e');
    }
  }
}
```

2024-02-15 16:10 UTC, KobayashiYoh commented on qiita_app/lib/widgets/app_title.dart
> +    return PreferredSize(
端末によってAppBarのレイアウト崩れが生じてしまっているため、修正お願いします
共通パーツをクラスごとに分けて再利用するという考えはとても良いです⭕️
<img src="https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/assets/82624334/49499489-6353-4b6e-948a-2d8b35b37f41" width="300">

2024-02-15 16:10 UTC, KobayashiYoh commented on qiita_app/lib/widgets/searchbar.dart
> +          hintStyle: const TextStyle(
`Search...`ではなく、`Search`ですね
修正お願いします🙏
<img width="366" alt="スクリーンショット 2024-02-16 1 06 05" src="https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/assets/82624334/1c6a1d34-69cb-4cad-bb40-7eb031c3efcc">

2024-02-15 16:10 UTC, KobayashiYoh commented on qiita_app/lib/widgets/text_app_title.dart
> +    );
FigmaでもStyleを共通化したりすることがあると思うのですが、FlutterもTextではなく、TextStyleを共通化するのが一般的かなと思われます

修正は任意ですし、テキストを共通化しようとする考えはとても良いと思います👍

2024-02-16 01:43 UTC, IwaseMio reviewed
appBarのとこコメントしましたー！

2024-02-16 01:43 UTC, IwaseMio commented on qiita_app/lib/widgets/app_title.dart
> +    this.showBottomDivider = true,
この行が反映されておらず、検索バーの下の線が見つかりません
<img src="https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/assets/132257044/c22c7353-45d7-4455-8194-816fd4aed5b0" width="300">

2024-02-22 15:11 UTC, azuma502 commented on qiita_app/lib/constants/app_colors.dart
> +  static const divider = Color(0xFFE0E0E0);
修正しました！

2024-02-22 15:12 UTC, azuma502 commented on qiita_app/lib/repository/qiita_repository.dart
> +                'Failed to fetch Qiita items. Status code: ${response.statusCode}');
なるほど！修正してみました！！

2024-02-22 15:14 UTC, azuma502 commented on qiita_app/lib/widgets/app_title.dart
> +    return PreferredSize(
動的に高さが変化するようにしてみました！

2024-02-22 15:14 UTC, azuma502 commented on qiita_app/lib/widgets/searchbar.dart
> +          hintStyle: const TextStyle(
修正しました！

2024-02-22 15:17 UTC, azuma502 commented on qiita_app/lib/widgets/text_app_title.dart
> +    );
TextStyleを共通化にしてみました！

>

2024-02-22 15:25 UTC, azuma502 commented on qiita_app/lib/pages/feed_page.dart
> +        showBottomDivider: true,
ここでtrueにしているので、反映されいる気はしています、、！
違うdividerのことでしょうか、？

2024-02-22 15:38 UTC, azuma502 commented on qiita_app/lib/widgets/app_title.dart
> +    this.showBottomDivider = true,
[qiita_app/lib/pages/feed_page.dart](https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/pull/2/files/e1f0264ec03d02fe981ff75e99b82588e26394f7#diff-6661afbacfe9b24996a93ea4d3a34664cb9904a5ae34218b24e5f53ac8b950f1)
で以下のコードがtrueになっているので反映されている気はしています、、
違うdividerのことでしょうか、？？

```dart
 showSearchBar: true,
 showBottomDivider: true,
```

2024-02-26 09:06 UTC, KobayashiYoh commented on qiita_app/lib/constants/app_colors.dart
> +  static const divider = Color(0xFFE0E0E0);
しっかり修正できています！

2024-02-26 09:07 UTC, KobayashiYoh commented on qiita_app/lib/repository/qiita_repository.dart
> +                'Failed to fetch Qiita items. Status code: ${response.statusCode}');
いいですね👍

2024-02-26 09:10 UTC, KobayashiYoh commented on qiita_app/lib/widgets/searchbar.dart
> +          hintStyle: const TextStyle(
しっかり修正できています✨

2024-02-26 09:17 UTC, KobayashiYoh commented on qiita_app/lib/widgets/text_app_title.dart
> +    );
AppColorのように、Textをサイズごとにコンポーネント化するというよりは、TextStylesを定数するイメージですね
命名やフォントサイズなどの中身はめちゃくちゃ適当な内容ですが、書き方としては以下のような感じです

```
import 'package:flutter/material.dart';
import 'package:qiita_app/constants/app_colors.dart';

class TextStyles {
  static const TextStyle titleLarge = TextStyle(
    fontFamily: 'Pacifico',
    fontSize: 24,
    color: AppColors.black,
  );

  static const TextStyle titleMedium = TextStyle(
    fontFamily: 'Pacifico',
    fontSize: 17,
    color: AppColors.black,
  );
}

```

2024-02-26 09:18 UTC, KobayashiYoh commented on qiita_app/lib/widgets/app_title.dart
> +    return PreferredSize(
惜しい！あとちょっとです！
<img src="https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/assets/82624334/4961cd96-2ace-44bf-bcf8-ced243fa9e16" width="300">

2024-02-26 09:36 UTC, KobayashiYoh commented on qiita_app/lib/widgets/app_title.dart
> +    return PreferredSize(
SafeAreaを活用してみましょう

2024-03-01 00:56 UTC, azuma502 commented on qiita_app/lib/widgets/text_app_title.dart
> +    );
修正してみました！

2024-03-01 00:56 UTC, azuma502 commented on qiita_app/lib/widgets/app_title.dart
> +    return PreferredSize(
修正してみました！

2024-03-05 14:54 UTC, KobayashiYoh commented on qiita_app/lib/widgets/app_title.dart
> +    return PreferredSize(
AppBarクラスを使わずにAppBarを実装するのであれば、以下のようにColumn内にSizedBoxを入れてレイアウトを調整してください。
テキスト上下の余白が無くなってしまっています。

```dart
Column(
              mainAxisSize: MainAxisSize.min,
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                const SizedBox(height: 11.0),
                Text(
                  title,
                  style: style ?? AppTextStyles.apptitle,
                ),
                const SizedBox(height: 19.0),
                if (showSearchBar) const SearchBarWithIcon(),
                if (showBottomDivider) SizedBox(height: dividerHeight),
              ],
            ),
```

2024-03-05 14:59 UTC, KobayashiYoh commented
レイアウト崩れが発生しているので修正お願いします
<img src="https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/assets/82624334/718d4306-d6d1-419a-9b7c-a4b25ca2d160" width="300">

2024-03-06 09:14 UTC, KobayashiYoh commented on qiita_app/lib/widgets/text_app_title.dart
> +    );
しっかり修正できています！
styleの命名もデザイナーさんらしい良い命名だと思いました👏

2024-03-07 12:17 UTC, KobayashiYoh commented
レイアウト修正しっかりできています👍
LGTM！

2024-03-07 12:17 UTC, KobayashiYoh approved these changes

2024-03-07 12:18 UTC, merged