tag詳細ページ作成
shinonome-inc/mobile_Mio_azuma_basic_flutter pull request #28
Opened 2024-03-25 09:45 UTC by azuma502

## 概要：tag詳細ページ作成

## CLIENT_IDとCLIENT_SECRET

## 実装した内容：tag詳細ページ作成

## UI

## 動作確認

https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/assets/114731756/4bbcc153-5e18-4af9-a0ea-50a7a49f6eed

## 参考

## その他

2024-03-25 14:43 UTC, azuma502 commented
ページネーションと記事表示モーダルつくる忘れたので作成します

2024-04-01 18:56 UTC, kota78 commented on qiita_app/lib/pages/tag_detail_list_page.dart
> +    setState(() {
細かすぎる点ですがアロー関数で1行で書けるのでオススメです。

2024-04-01 18:56 UTC, kota78 commented on qiita_app/lib/widgets/app_title.dart
> +                  const SizedBox(height: 11),
すみません、これってfigmaでいうとどの部分ですか？
見つけられなかったので教えて頂きたいです🙇‍♂️

figmaで11のようにキリの悪い(2,4の倍数でない)数値が指定されていた場合、自分はfigmaの仕様で変な大きさになっているのかなと思い10か12のように直して実装していたのですが、指定通りの方が良いでしょうか...？
デザイナーの方の意見が聞きたいです。

2024-04-01 18:56 UTC, kota78 commented on qiita_app/lib/widgets/app_title.dart
>      final Color dividerColor = Theme.of(context).dividerColor;
themeを使った実装good!!

2024-04-01 18:56 UTC, kota78 commented on qiita_app/lib/pages/tag_detail_list_page.dart
> +                child: ListView.builder(
この辺とかfeedpageと同じ気がするので1つにまとめた方が良いのではと思いました。
スクロール時の読み込み処理も使い回しできる気がします。

2024-04-02 12:09 UTC, azuma502 commented on qiita_app/lib/pages/tag_detail_list_page.dart
> +                child: ListView.builder(
スクロールの読み込み共通化してみました！

2024-04-02 13:35 UTC, azuma502 commented on qiita_app/lib/widgets/app_title.dart
> +                  const SizedBox(height: 11),
![スクリーンショット 2024-04-02 083031](https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/assets/114731756/f4860220-efe3-46d4-8f84-cdcb0a9eb784)
タイトル上の9pxのところです、

> figmaで11のようにキリの悪い(2,4の倍数でない)数値が指定されていた場合、自分はfigmaの仕様で変な大きさになっているのかなと思い10か12のように直して実装していたのですが、指定通りの方が良いでしょうか...？
デザイナーの方の意見が聞きたいです。

デザインとしては、「4,8の倍数、または偶数」にした方がいいと思います！
今回「11」になってしまったのは、以前のレビューでapptitleの大きさが小さいデバイスだとエラーがでてしまい数値を色々いじってしまった結果です、
でも結局、エラーがでてしまう根本的な原因が違ったので、偶数の「１０」に変更しました！

2024-04-03 07:54 UTC, azuma502 commented on qiita_app/lib/pages/tag_detail_list_page.dart
> +    setState(() {
コードを書き換えたので、まだアロー関数必要だったりしますでしょうか？？

2024-04-05 11:20 UTC, kota78 commented on qiita_app/lib/widgets/app_title.dart
> +                  const SizedBox(height: 11),
ナイスです！ありがとうございます。

2024-04-05 11:21 UTC, kota78 commented on qiita_app/lib/pages/tag_detail_list_page.dart
> +                child: ListView.builder(
すぎょい

2024-04-05 12:35 UTC, kota78 commented on qiita_app/lib/pages/tag_detail_list_page.dart
> +    setState(() {
不要です！

2024-04-05 13:14 UTC, KobayashiYoh requested changes
コメントしました。

2024-04-05 13:14 UTC, KobayashiYoh commented on qiita_app/lib/widgets/app_title.dart
> +                    ),
何らかの変更が原因で、SearchBarの"Search"の文字が太くなってしまっているので、修正お願いします。

2024-04-05 13:14 UTC, KobayashiYoh commented on qiita_app/lib/widgets/tag_container.dart
> +                ),
今回の変更が原因でTagContainerのレイアウトが崩れてしまっているため、修正お願いします。
タスクと関係のない箇所のコードの変更はなるべく最小限に押さえておくと、今回のような不具合が発生しにくくなるのでおすすめです。

2024-04-05 13:14 UTC, KobayashiYoh commented on qiita_app/lib/pages/tag_detail_list_page.dart
> +  final Tag tag;
タグ詳細画面の実装自体はしっかりできています👍
天才か！？

2024-04-05 14:26 UTC, azuma502 commented on qiita_app/lib/widgets/tag_container.dart
> +                ),
修正してみました！

2024-04-05 14:26 UTC, azuma502 commented on qiita_app/lib/widgets/app_title.dart
> +                    ),
修正してみました！

2024-04-05 14:43 UTC, KobayashiYoh approved these changes
<img src="http://media.tumblr.com/b999d6fa94d40545edb2dac70623e070/tumblr_inline_n2ztfg6zr01qaxsyz.gif" width="400">

2024-04-05 14:44 UTC, KobayashiYoh commented on qiita_app/lib/widgets/app_title.dart
> +                    ),
しっかり修正できています！

2024-04-05 14:44 UTC, KobayashiYoh commented on qiita_app/lib/widgets/tag_container.dart
> +                ),
しっかり修正できています！

2024-04-05 14:47 UTC, merged