Settingpage UI
shinonome-inc/mobile_Mio_azuma_basic_flutter pull request #3
Opened 2024-02-10 14:35 UTC by IwaseMio

## 概要
SettingpageのUIと、バージョンの取得を実装しました

## CLIENT_IDとCLIENT_SECRET

## 実装した内容
SettingpageのUIと、バージョンの取得を実装しました

## UI
<img src="https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/assets/132257044/b7f08b67-92c2-4d7e-84b4-fd1b8e7d69cf" width="300">

## 動作確認

## 参考

## その他
よろしくお願いします！

2024-02-14 13:57 UTC, azuma502 reviewed
コメントしました～！！

2024-02-14 13:57 UTC, azuma502 commented on qiita_app/lib/pages/setting_page.dart
> +          ),
同じUIで同じコードが繰り返されているので、コンポーネント作ってもいいかなと思いました！

2024-02-14 14:00 UTC, azuma502 commented on qiita_app/lib/pages/setting_page.dart
> +          ),
同じUIで同じコードが繰り返されているので、コンポーネント作ってもいいかなと思いました！

2024-02-22 02:44 UTC, Yoshida-koshi requested changes
コメントしました〜

2024-02-22 02:44 UTC, Yoshida-koshi commented on qiita_app/lib/pages/setting_page.dart
> +      ),
今回はappBarは似ている部分が多いので、共通化した方がいいですね！

2024-02-22 02:44 UTC, Yoshida-koshi commented on qiita_app/lib/widgets/setting_item.dart
> +class SectionTitle extends StatelessWidget {
1つのファイルに複数のclassは可読性の観点から良くないです！
今回はファイル名がsetting_item.dartなので、classはSettingItemだけでいいと思います！

2024-02-22 02:44 UTC, Yoshida-koshi commented on qiita_app/lib/widgets/setting_item.dart
> +        style: const TextStyle(fontSize: 12, color: Colors.grey),
ここのColorもFigmaに定義されているので、それに修正してみてください！

2024-02-22 02:44 UTC, Yoshida-koshi commented on qiita_app/lib/widgets/setting_item.dart
> +      tileColor: Colors.white,
ここもFigmaに定義されているので、修正してみてください！

2024-02-22 02:44 UTC, Yoshida-koshi commented on qiita_app/lib/widgets/setting_item.dart
> +}
今回はDividerだけなので、わざわざclassを作って共通化するのは大袈裟かなと思います！
この場合は逆にコードの可読性が下がるので、気を付けてください！

2024-02-22 02:44 UTC, Yoshida-koshi commented on qiita_app/lib/pages/setting_page.dart
> +  String version = 'v0.0.0';
versionはsetVersion関数にしか使っていないと思うので、その関数内で定義した方がいいと思います！

2024-02-22 02:44 UTC, Yoshida-koshi commented on qiita_app/lib/pages/setting_page.dart
> +    PackageInfo packageInfo = await PackageInfo.fromPlatform();
ちゃんとパッケージ参照していて素晴らしいですね！👍

2024-02-22 02:44 UTC, Yoshida-koshi commented on qiita_app/lib/widgets/setting_item.dart
> +    this.height = 1.0,
細かいですけど、heightは0.5ですね！

<img width="1512" alt="スクリーンショット 2024-02-22 11 43 26" src="https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/assets/85224998/03734ff5-5b73-4c65-966a-fba522d045ca">

2024-02-29 03:27 UTC, kota78 commented on qiita_app/lib/pages/setting_page.dart
> +
めちゃめちゃ良いと思います！！！
修正は不要ですが、次から使えるyoさんから授かった知恵を書いておきます。
以下のように、MaterialApp→theme→dividerTheme内でDividerのthemeが指定できます。これを使うと、どこでDividerを使っても同じデザインになるように初期値を設定することができます。

```
MaterialApp(
      title: 'qiita_app',
      theme: ThemeData(
        dividerTheme: const DividerThemeData(
          color: AppColors.divider,
        ),
      ),
      home: const TopPage(title: 'Qiita Feed App'),
    );
```

2024-02-29 03:27 UTC, kota78 commented on qiita_app/lib/pages/setting_page.dart
> +    return Divider(
今回はこの書き方が適切だと思いますが、関数内の処理が少ない時に使える「アロー関数」の紹介です。
（既にご存知かもしれませんが）
例1,2は上下一緒の意味です。
例1
```
Widget buildCustomDivider() {
    return Divider()
}
```
と
```
Widget buildCustomDivider() => Divider();
```
例2
```
setState(() {
                a = 0;
              });
```
と
```
setState(() => a = 0);
```

2024-03-01 11:32 UTC, KobayashiYoh commented on qiita_app/lib/pages/setting_page.dart
> +  String version = 'v0.0.0';
version変数Textで使ってますよ

2024-03-07 13:36 UTC, Yoshida-koshi commented
appBarの色とbodyの色が全く同じになっちゃっていますね！
これだと見分けがつかないので、Figmaを参考に修正してみてください！

<img src="https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/assets/85224998/be5d9067-5649-472a-85c8-6c00d9dab67f" width="300">

2024-03-07 14:24 UTC, Yoshida-koshi approved these changes
LGTM！お疲れ様でした！

2024-03-07 14:25 UTC, merged