マイページ作成
shinonome-inc/mobile_Mio_azuma_basic_flutter pull request #32
Opened 2024-03-29 02:53 UTC by azuma502

## 概要：マイページ作成しました

## CLIENT_IDとCLIENT_SECRET

## 実装した内容：マイページ作成しました

## UI

## 動作確認

## 参考

## その他

2024-04-10 03:10 UTC, Yuki0316 commented
実装お疲れ様です！

2024-04-10 04:00 UTC, Yuki0316 commented
実装お疲れ様です！
一点気になった点がありましたので、コメントします！

下記画像の青で囲んだアイコンや文字部分をタップすると、記事詳細モーダルが出てくるのですが、赤で囲んだ余白部分では記事詳細モーダルが出てきませんでした。
余白部分でもタップできるようにしておくといいと思います！
![気になった点](https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/assets/102783724/059fba8c-c94a-4645-9ba0-56411aae8281)

2024-04-10 15:12 UTC, azuma502 commented
> 実装お疲れ様です！ 一点気になった点がありましたので、コメントします！
> 
> 下記画像の青で囲んだアイコンや文字部分をタップすると、記事詳細モーダルが出てくるのですが、赤で囲んだ余白部分では記事詳細モーダルが出てきませんでした。 余白部分でもタップできるようにしておくといいと思います！ ![気になった点](https://private-user-images.githubusercontent.com/102783724/321075149-059fba8c-c94a-4645-9ba0-56411aae8281.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NjIyMjcsIm5iZiI6MTcxMjc2MTkyNywicGF0aCI6Ii8xMDI3ODM3MjQvMzIxMDc1MTQ5LTA1OWZiYThjLWM5NGEtNDY0NS05YmEwLTU2NDExYWFlODI4MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQxNTEyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Yjg5MjczYmZjOWY0MjI5NGVkYzY0ZjU0YWQyNWVhMGRlZjVkMzM5NTgwNjJkZGY4YTc5ODIyNjE4NjRhZTJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.37n9p2HMCDk9bGf0oJ-1FiqLQij5RR-JFcVRkiHRZds)

詳しくありがとうございます！！
修正します！

2024-04-11 03:01 UTC, azuma502 commented
<img width="383" alt="スクリーンショット 2024-04-11 12 00 03" src="https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/assets/114731756/b9be7c69-13f1-420f-8d18-15f6dad0e3a7">
マイページの投稿記事にユーザアイコンがなかったため、UI自体も変更しました。
また、余白タップもできるようにしました。

2024-04-11 03:44 UTC, Yuki0316 commented
余白部分タップ確認できました！私が見逃していたUIについてもOKです！LGTMです👌

2024-04-13 02:06 UTC, TAK848 requested changes
コメントしました！ご確認お願いします！

2024-04-13 02:06 UTC, tak848 commented on qiita_app/ios/Runner.xcodeproj/project.pbxproj
> +
余計に差分入ってしまった感じですかね…？

2024-04-13 02:06 UTC, tak848 commented on qiita_app/lib/models/user.dart
> +}
空行や空白が不規則に入ってしまっている気がするんだけど，オートフォーマットってセットされてたりしますかね…？よければ是非設定を！
https://nobushiueshi.com/flutterandroid-studio%E3%81%A8visual-studio-code%E3%81%A7%E3%81%AE%E3%82%B3%E3%83%BC%E3%83%89%E6%95%B4%E5%BD%A2%E3%81%AE%E4%BB%95%E6%96%B9/
↓auto formatかけるとこうなるかと
```suggestion
class User {
  final String profileImageUrl;
  final String name;
  final String id;
  final String description;
  final int followeesCount;
  final int followersCount;
  final String url;

  User({
    required this.profileImageUrl,
    required this.name,
    required this.id,
    required this.description,
    required this.followeesCount,
    required this.followersCount,
    required this.url,
  });

  factory User.fromJson(Map<String, dynamic> json) {
    return User(
      profileImageUrl: json['profile_image_url'] as String,
      name: json['name'] as String? ?? '', // nullの場合、デフォルト値として空文字列を設定
      id: json['id'] as String,
      description:
          json['description'] as String? ?? '', // nullの場合、デフォルト値として空文字列を設定
      followeesCount: json['followees_count'] ?? 0,
      followersCount: json['followers_count'] ?? 0,
      url: json['url'] as String? ?? '',
    );
  }
}
```

2024-04-13 02:06 UTC, tak848 commented on qiita_app/lib/pages/my_page.dart
> +// import 'package:qiita_app/pages/my_page_notlogin.dart';
PRでは関係ないコメントは消しておきましょー！

2024-04-13 02:06 UTC, tak848 commented on qiita_app/lib/pages/my_page.dart
> +    //   return const MyPageNotLogin();
ここも！

2024-04-13 02:06 UTC, tak848 commented on qiita_app/lib/repository/qiita_repository.dart
>  // import 'dart:html';
今回の差分では無いけどここも！

2024-04-13 02:06 UTC, tak848 commented on qiita_app/lib/pages/my_page.dart
> +    } else {
ifのブロックで，例外パターンはreturnしているので，ここのelseは無くても良いかと思います！
例外パターンを最初に序列して全てはじいた上で，通常パターンのネストを減らそう！というイメージ

```
if (なにかの例外パターン) {
    return YYY
} else if (他の例外パターン) {
    return ZZZ
} else {
    // 通常時の表示
    return XXX
}
```
よりも
```
if (なにかの例外パターン) {
    return YYY
}
if (他の例外パターン) {
    return ZZZ
}

// 通常時の表示
return XXX
```
のほうが，通常時の表示のネストが減って，FlutterやReactでは好まれる（はず）

2024-04-13 02:06 UTC, tak848 commented on qiita_app/lib/widgets/user_info_container.dart
|![Screenshot_20240413-103638](https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/assets/41906969/c272256e-69be-48b7-b1a0-411e0376e554)|![Screenshot_20240413-104721](https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/assets/41906969/40d83f93-937e-459b-a340-2d4ec530d407)|
|-|-|

nameやdescriptionが無いときに間延びしてしまっているので対策してあげると良いかと思います！
nameが無いときはidを入れてあげるとか，descriptionが無いときはそもそもスペース入れないとか…
reposirotyの
`final url = Uri.parse('${Urls.qiitaBaseUrl}/authenticated_user');`
を
`final url = Uri.parse('${Urls.qiitaBaseUrl}/users/yametaro');`
とかみたいに変えてあげると一応色々試せます

2024-04-13 02:06 UTC, TAK848 commented on qiita_app/lib/pages/my_page.dart
> +            UserInfoContainer(user: loggedInUser!),
[後回しでもOK]
ここのキャストの影響で，インターネット未接続時などにnull checkに失敗してエラーになってしまっているので，対策しましょう！（一度バグとして起票して後で修正でも良いと思います！）

2024-04-14 03:55 UTC, azuma502 commented on qiita_app/ios/Runner.xcodeproj/project.pbxproj
> +
消しました！

2024-04-14 03:56 UTC, azuma502 commented on qiita_app/lib/models/user.dart
> +}
設定してなかったです、、auto format設定してみました！

2024-04-14 03:57 UTC, azuma502 commented on qiita_app/lib/pages/my_page.dart
> +    //   return const MyPageNotLogin();
消しました！

2024-04-14 03:57 UTC, azuma502 commented on qiita_app/lib/repository/qiita_repository.dart
>  // import 'dart:html';
消しました！

2024-04-14 03:58 UTC, azuma502 commented on qiita_app/lib/pages/my_page.dart
> +    } else {
なるほど！
修正してみました！！

2024-04-14 04:13 UTC, azuma502 commented on qiita_app/lib/widgets/user_info_container.dart
なるほど！！
nameがない時→idを
descriptionがない時→スペース無くす
で修正してみました！

2024-04-14 04:13 UTC, azuma502 commented on qiita_app/lib/pages/my_page.dart
> +            UserInfoContainer(user: loggedInUser!),
気づかなかったです、、
loggedInUserがnullのときexceptionを投げるように設定してみました！

2024-04-14 04:15 UTC, azuma502 commented
細かいところまでレビューありがとうございます！
修正してみたのでご確認お願いいたします！

2024-04-14 09:33 UTC, TAK848 approved these changes
LGTM!!
ユーザーが見つからない時，投稿記事のバーだけ出てきて何も表示されない挙動になってしまっていますが，ネットワークエラーの対応などもあると思うのでそのあたりでやってもらえれば！！

2024-04-14 09:35 UTC, TAK848 commented on qiita_app/lib/pages/my_page.dart
> +            UserInfoContainer(user: loggedInUser!),
エラー画面の表示は無くなったのでOKです！

メモ: https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/pull/32#pullrequestreview-1999528815

2024-04-14 10:13 UTC, merged