エラー画面
shinonome-inc/mobile_Mio_azuma_basic_flutter pull request #34
Opened 2024-04-08 07:17 UTC by IwaseMio

## 概要
エラー画面を実装しました。

## CLIENT_IDとCLIENT_SECRET

## 実装した内容
ネットワークエラー
ログインしていないときのマイページ画面

## UI

## 動作確認

## 参考

## その他

2024-04-16 15:29 UTC, Yuki0316 commented
遅くなってしまいすみません🙇‍♀️LGTMです！

2024-04-18 23:11 UTC, TAK848 requested changes

2024-04-18 23:11 UTC, tak848 commented on qiita_app/lib/pages/feed_page.dart
> +          }
elseまでの認知負荷が高くなっているように見えて，以下のコメントみたいにアーリーリターンしてあげると見通し良くなるかと思います！
https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/pull/32#discussion_r1563536825
今elseの中に入っているreturnが本来表示したい内容で，他は様々なパターンを別途列挙しているにすぎないので…

else ifもただのifにしても良いかも

2024-04-18 23:11 UTC, TAK848 commented on qiita_app/lib/pages/tag_page.dart
> +          } else {
[IMO]
hasError->NetworkErrorと，広義なエラーからNetworkという一つのエラータイプが返ってきていて，他のエラーは…？となっているので，
hasErrorの命名具体的にした方が良いかも

2024-04-18 23:46 UTC, IwaseMio commented on qiita_app/lib/pages/tag_page.dart
> +          } else {
hasError->hasNetworkErrorと修正しました！

2024-04-18 23:46 UTC, IwaseMio commented on qiita_app/lib/pages/feed_page.dart
> +          }
修正しました！

2024-04-18 23:48 UTC, TAK848 approved these changes
LGTM!!

2024-04-18 23:53 UTC, merged