ログアウト機能作成
shinonome-inc/mobile_Mio_azuma_basic_flutter pull request #38
Opened 2024-04-18 07:09 UTC by azuma502

## 概要：ログアウト機能を作成

## CLIENT_IDとCLIENT_SECRET
https://drive.google.com/file/d/1eDe853r65nVN0CZR-UD7GrW_24_RE6Sk/view?usp=drive_link

## 実装した内容：ログアウト機能を作成

## UI
[logout.webm](https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/assets/114731756/c36a1e8f-db24-4521-9d25-2810f8bfb398)

## 動作確認

## 参考

## その他

2024-04-20 16:10 UTC, KobayashiYoh reviewed
今後の案件参加を見据えて多めにコメントしました。
どのコメントに関しても今回修正する必要はないので、ざっくり目を通し、コース修了後に時間があれば取り組んでみてください。

2024-04-20 16:10 UTC, KobayashiYoh commented on qiita_app/lib/pages/my_page.dart
>      if (hasNetworkError) {
ifでたくさん区切っていますが、2つ目以降のif文はelse if文に置き換えても良いのかなと思いました。
間違いとかではないので修正の必要はないです！

2024-04-20 16:10 UTC, KobayashiYoh commented on qiita_app/lib/pages/my_page_notlogin.dart
> +            ),
ご存知かもしれませんが、文字列は`\n`で改行することができます。
今回の場合、Textを2つに分けるよりも、1つのTextで改行を利用する方が一般的な実装方法かなと思います。
今回修正の必要はありませんが、頭に入れておいてください。
```dart
            const Text(
              'マイページの機能を利用するには\nログインを行っていただく必要があります。',
              style: AppTextStyles.h3BasicSecondary,
            ),
```

2024-04-20 16:10 UTC, KobayashiYoh commented on qiita_app/lib/pages/setting_page.dart
> +              }
あくまで案なので修正の必要はありませんが、僕だったらonTapの中を以下のように書くかなと思います。

```dart
onTap: () async {
    try {
      await QiitaRepository.logout();
    } catch (e) {
      if (!context.mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('ログアウトに失敗しました: $e')),
      );
    }
    if (!context.mounted) return;
    Navigator.of(context).pushAndRemoveUntil(
      MaterialPageRoute(
        builder: (context) => const TopPage(title: 'Qiita Feed App'),
      ),
      (Route<dynamic> route) => false,
    );
```

ポイントは以下の3つになります。
### 1. try文の中はシンプルに
try文の中身はできるだけシンプルにするのが好ましいのかなと思います。
僕は基本的にtry文の中身は失敗の可能性がある処理（通信など）のみを書くようにしています。

### 2. 早期リターンを使う
if文とreturnを組み合わせて早期リターンを行うことにより、インデントが深くなるのを防ぐことができます。
公式ドキュメントのコードでも、早期リターンを採用しています。
https://dart.dev/tools/linter-rules/use_build_context_synchronously

2024-04-20 16:10 UTC, KobayashiYoh commented on qiita_app/lib/repository/qiita_repository.dart
> +  }
Qiita APIをはじめとした多くのAPIではアクセストークン失効機能が用意されています。
ログアウトの際に発行したアクセストークンを失効させるのが好ましいです。
https://qiita.com/api/v2/docs#delete-apiv2access_tokensaccess_token

2024-04-20 16:10 UTC, KobayashiYoh commented on qiita_app/lib/repository/qiita_repository.dart
> +  }
アクセストークンのような機密情報を扱う際はshared_preferencesよりもflutter_secure_storageの方がいいかもしれません。
shared_preferencesはデータを平文（暗号化しない）で端末に保存しますが、flutter_secure_storageはデータを暗号化して端末に保存します。
https://pub.dev/packages/flutter_secure_storage

2024-04-20 16:10 UTC, KobayashiYoh commented on qiita_app/lib/pages/setting_page.dart
> +            onTap: () async {
現状だと「ログアウトする」が常時表示されているので、ログイン時にはログアウトボタンを表示し、未ログイン時にはログアウトボタンを非表示にしておくといいかもしれませんね。

2024-04-20 16:15 UTC, KobayashiYoh commented
## 今回修正してほしいこと
pubspec.yamlの`connectivity_plus`が原因で環境によってはビルドエラーが発生しているみたいです。
https://github.com/fluttercommunity/plus_plugins/issues/2839

このプロジェクトでconnectivity_plusは使われていないみたいなので、削除しておきましょう。
不要なコードは消すという習慣をつけておきましょう。

## 次回のプルリク提出までに意識してほしいこと
初回レビュワーの方が必ず必要になるので、プルリクの「CLIENT_IDとCLIENT_SECRET」の項目に.envのダウンロードリンクを貼っておきましょう。

2024-04-20 16:23 UTC, KobayashiYoh requested changes
## 今回修正してほしいこと
pubspec.yamlの`connectivity_plus`が原因で環境によってはビルドエラーが発生しているみたいです。
https://github.com/fluttercommunity/plus_plugins/issues/2839

このプロジェクトでconnectivity_plusは使われていないみたいなので、削除しておきましょう。
不要なコードは消すという習慣をつけておきましょう。

## 次回のプルリク提出でやってほしいこと
初回レビュワーの方が必ず必要になるので、プルリクの「CLIENT_IDとCLIENT_SECRET」の項目に.envのダウンロードリンクを貼っておきましょう。

## よかった点
azumaさんのコードを見ていて、初期と比べてかなり技術力が上がっている印象を受けました！
技術力などの実力に加え、毎日の学習時間確保や進捗共有を本当によく頑張っているなと思い、僕も見習わないといけないなと思いました！
コース修了まであと少しですが、頑張っていきましょう🔥

2024-04-21 05:29 UTC, azuma502 commented
丁寧にレビューをありがとうございます！！ありがたいです
最終課題終わったら修正してみます！！

2024-04-21 05:58 UTC, azuma502 commented
connectivity_plus削除しました！！
お手隙の際に確認をお願いいたします！！

2024-04-21 06:08 UTC, KobayashiYoh approved these changes

2024-04-21 06:08 UTC, KobayashiYoh commented
LTGM🎉

2024-04-21 06:08 UTC, merged