タグ画面を作成しました
shinonome-inc/mobile_Mio_azuma_basic_flutter pull request #4
Opened 2024-02-11 14:46 UTC by IwaseMio

## 概要

## CLIENT_IDとCLIENT_SECRET

## 実装した内容

## UI

## 動作確認

## 参考

## その他

2024-02-21 13:42 UTC, Ryunosuke1114 reviewed
いい感じに実装できてると思います🙆‍♂️
自分のコメントの修正は任意&ちょっとした質問程度なので2次レビュー飛ばしちゃっても大丈夫です、あんまりコメント長引くと自分夜しか見れないので1次レビューに何日もかけてしまうので。。。笑

2024-02-21 13:42 UTC, Ryunosuke1114 commented on qiita_app/lib/widgets/text_app_title.dart
> +class TextAppTitle extends StatelessWidget {
text_app_titleとapp_titleを分けている理由ってあったりしますか？

2024-02-21 13:42 UTC, Ryunosuke1114 commented on qiita_app/lib/repository/qiita_repository.dart
>  class QiitaRepository {
修正はしなくていいのですが、あまりrepositoryという命名が正しいと思っていなくて、多くのアーキテクチャではrepositoryは具体的な実装を呼び出し側から隠蔽するためのインターフェイスを定義する層なのでこのファイルにはもっと適切な命名があるのではないかと思っています。。Data Sorceとか、
https://codewithandrea.com/articles/flutter-app-architecture-riverpod-introduction/
※上記の記事のData Layerあたりの話です

2024-02-22 03:07 UTC, Yoshida-koshi commented
フォロワーが上2つで左に寄っているので、改行した後も位置は真ん中になるようにしてみてください！

<img src="https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/assets/85224998/64644e40-915f-4fb7-86b6-9a4e34110a48" width="300">

2024-02-22 03:12 UTC, Yoshida-koshi commented
画面が小さいAndroidだと以下の画像のようにエラーが出てしまいますね！
タグの項目の高さを可変にすれば治ると思うので、修正してみてください！

<img src="https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/assets/85224998/3122f1ed-c7a5-454d-8b04-fe0be7531383" width="300">

2024-02-22 03:33 UTC, Yoshida-koshi requested changes
コメントしました〜

2024-02-22 03:33 UTC, Yoshida-koshi commented on qiita_app/lib/constants/app_colors.dart
> +  static const black = Colors.black;
appColorクラスはFigmaで定義されているColorを使い回すためにあるので、`Colors.black`みたいな書き方は避けたいですね！
Figmaに書いてあるHexColorをもとに修正してみてください！

2024-02-22 03:33 UTC, Yoshida-koshi commented on qiita_app/lib/repository/qiita_repository.dart
> +      return jsonResponse.map((data) => Tag.fromJson(data)).toList();
ここの処理が複雑でぱっと見何を返しているのかわからないので、一旦変数に格納してから、returnした方が見やすくなっていいと思います！

2024-02-22 03:33 UTC, Yoshida-koshi commented on qiita_app/lib/widgets/text_app_title.dart
> +}
Textだけだったら、classで分ける必要は無いと思います！

2024-03-20 06:42 UTC, Yoshida-koshi commented on qiita_app/lib/repository/qiita_repository.dart
> +      return jsonResponse.map((data) => Tag.fromJson(data)).toList();
OKです！

2024-03-20 06:44 UTC, Yoshida-koshi commented on qiita_app/lib/widgets/text_app_title.dart
> +}
OKです！

2024-03-20 07:22 UTC, Yoshida-koshi commented
やはりまだ小さいAndroidだと枠から外れてしまいますね！

<img src="https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/assets/85224998/d83c4649-88b4-4817-baa8-8d915ac15fba" width="300">

2024-03-24 09:12 UTC, azuma502 commented
@IwaseMio 
UI修正してみました～！

2024-03-24 14:49 UTC, KobayashiYoh commented
これでどうでしょうか？
```dart
Expanded(
            child: Text(
              '記事件数:${tag.itemsCount}',
              style: const TextStyle(
                fontSize: 12,
                color: AppColors.secondary,
              ),
            ),
          ),
          const SizedBox(height: 8.0),
          Expanded(
            child: Text(
              'フォロワー数:${tag.followersCount}',
              overflow: TextOverflow.ellipsis,
              style: const TextStyle(
                fontSize: 12,
                color: AppColors.secondary,
              ),
            ),
          ),
```

2024-03-24 14:53 UTC, azuma502 commented
UI修正しました！

2024-03-24 14:56 UTC, KobayashiYoh approved these changes
Koshiくんの代わりに二次レビューの修正確認しました！
LTGMです✨

2024-03-24 14:56 UTC, merged