設定画面モーダル作成
shinonome-inc/mobile_Mio_azuma_basic_flutter pull request #5
Opened 2024-03-07 15:53 UTC by azuma502

## 概要：設定画面モーダルを作成しました

## CLIENT_IDとCLIENT_SECRET

## 実装した内容：設定画面モーダルを作成しました

## UI
<img src="https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/assets/114731756/ec6abba7-8382-4072-9ca1-8169e47bb822" width="300">

## 動作確認

## 参考

## その他

2024-03-08 02:12 UTC, KobayashiYoh requested changes
コメントしました。
SettingsPageの変更が差分に含まれていないので修正お願いします🙏

2024-03-08 02:12 UTC, KobayashiYoh commented on qiita_app/lib/constants/app_text_style.dart
> +  );
スタイルの定義がデザイナーさんっぽくていいですね👍

2024-03-08 02:12 UTC, KobayashiYoh commented on qiita_app/lib/widgets/app_bottom_modal_sheet.dart
> +  final bool showBottomDivider;
FeedPageでの使い回しを意識できていていいですね👍

2024-03-08 02:12 UTC, KobayashiYoh commented on qiita_app/lib/widgets/app_bottom_modal_sheet.dart
> +              ),
修正は任意ですが、画面下の文字が切れているのが気になりました。
恐らく、余白設定の方法が原因だと思われます。
<img src="https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/assets/82624334/70b866b6-9766-4555-82d4-4cfe88cb6ec3" width="300">

<img width="225" alt="スクリーンショット 2024-03-08 11 05 04" src="https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/assets/82624334/bca2ec4f-500f-4670-b7d9-268815d4435b">

2024-03-08 02:12 UTC, KobayashiYoh commented on qiita_app/lib/constants/texts.dart
> +  static const String privacyPolicyText = '''
👍

2024-03-11 05:43 UTC, yukik8 reviewed
コンポーネント化もしっかりできていて綺麗なコードだと思います！！LGTMです🙆

2024-03-11 11:53 UTC, KobayashiYoh commented on qiita_app/lib/widgets/app_bottom_modal_sheet.dart
> +              ),
プルリクに添付された画像だけだと気づけなかったのですが、画面上部の余白も切れているので今後修正お願いします。
これ以上長引いてもアレなので、今回はマージします。

2024-03-11 11:53 UTC, KobayashiYoh approved these changes

2024-03-11 11:54 UTC, KobayashiYoh commented
LGTMです

2024-03-11 11:54 UTC, merged