WIP:記事ページsa
shinonome-inc/mobile_Mio_azuma_basic_flutter pull request #7
Opened 2024-03-22 01:31 UTC by IwaseMio

## 概要

## CLIENT_IDとCLIENT_SECRET

## 実装した内容

## UI

## 動作確認

## 参考

## その他

2024-03-25 08:21 UTC, KobayashiYoh requested changes
コメントしました。

2024-03-25 08:21 UTC, KobayashiYoh commented on qiita_app/lib/widgets/app_bottom_modal_sheet.dart
> -                child: SingleChildScrollView(
<img src="https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/assets/82624334/7e3277fb-875a-416b-a476-541028550325" width="300">

不要な余白ができちゃってるかも
プライバシーポリシーと利用規約の余白は必要かもしれませんが、記事の表示の余白は不要なので修正お願いします。

2024-03-25 08:21 UTC, KobayashiYoh commented on qiita_app/lib/widgets/article_container.dart
> +        UniqueKey key = UniqueKey();
これってどういう処理ですか？

2024-03-25 08:21 UTC, KobayashiYoh commented on qiita_app/lib/widgets/article_container.dart
>                ),
WebViewしっかり使いこなせていますね👍

2024-03-25 08:56 UTC, KobayashiYoh approved these changes
しっかり修正できています！
一次レビューLGTM🎉

2024-03-25 08:57 UTC, IwaseMio commented on qiita_app/lib/widgets/app_bottom_modal_sheet.dart
> -                child: SingleChildScrollView(
修正しました！

2024-03-28 07:41 UTC, taka392 commented
LGTMです🎉
次の課題に進んでください

2024-03-28 07:42 UTC, merged